name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --only=production
      - name: Clean up unnecessary files
        run: |
          # Remove old SQLite files that might cause issues
          rm -f *.db *.db-wal *.db-shm
          # Remove any large files that shouldn't be deployed
          find . -name "*.mp4" -delete
          find . -name "*.avi" -delete
          find . -name "*.mov" -delete
          find . -name "*.wmv" -delete
          # Remove test files
          find . -name "*.test.*" -delete
          find . -name "*.spec.*" -delete
          echo "Cleanup completed"
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
      - name: Create .env file
        run: |
          echo "ELEVEN_LABS_API_KEY=${{ secrets.ELEVEN_LABS_API_KEY }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          # Ensure NEXTAUTH_URL is set for Azure deployment if not in secrets
          if [ -z "${{ secrets.NEXTAUTH_URL }}" ]; then
            echo "NEXTAUTH_URL=https://lively-flower-0f6dae80f.azurestaticapps.net" >> .env
          fi
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
          echo "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" >> .env
          echo "AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}" >> .env
          echo "AZURE_OPENAI_DEPLOYMENT_NAME=${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}" >> .env
          echo "AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }}" >> .env
          echo "UPLOADTHING_TOKEN=${{ secrets.UPLOADTHING_TOKEN }}" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
          echo "RESEND_AUDIENCE_ID=${{ secrets.RESEND_AUDIENCE_ID }}" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "NODE_ENV=production" >> .env
          echo "BUILD_STATIC=false" >> .env
          echo "GITHUB_SHA=${{ github.sha }}" >> .env
      - name: Optimize for deployment
        run: |
          # Build the application
          npm run build
          # Remove unnecessary files from standalone build
          rm -rf .next/standalone/node_modules/.cache
          rm -rf .next/standalone/.git
          rm -rf .next/standalone/node_modules/.bin
          # Remove dev dependencies from standalone
          cd .next/standalone && npm prune --production --silent || true
          # Remove unnecessary files to reduce size
          find . -name "*.map" -delete
          find . -name "*.d.ts" -delete
          find . -name "*.test.*" -delete
          find . -name "*.spec.*" -delete
          # Create health check file for faster startup
          echo '{"status":"ready","timestamp":"$(date -u +%Y-%m-%dT%H:%M:%SZ)"}' > public/health.json
          # Check deployment size
          du -sh .next/standalone
          echo "Deployment size check completed"
      - name: Check deployment size
        run: |
          echo "=== DEPLOYMENT SIZE ANALYSIS ==="
          du -sh .next/standalone
          echo "Largest directories:"
          du -sh .next/standalone/* | sort -hr | head -10
          echo "Total file count:"
          find .next/standalone -type f | wc -l
          echo "=== END ANALYSIS ==="
          
          # Check if size is reasonable (should be under 250MB for Azure Static Web Apps)
          SIZE=$(du -sm .next/standalone | cut -f1)
          if [ "$SIZE" -gt 200 ]; then
            echo "⚠️  WARNING: Deployment size is ${SIZE}MB, which is close to Azure Static Web Apps limit"
          else
            echo "✅ Deployment size is ${SIZE}MB, which is acceptable"
          fi
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        timeout-minutes: 30
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_FLOWER_0F6DAE80F }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: ".next/standalone" # Built app content directory - optional
          github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######
        continue-on-error: false

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
